import "server-only";

import type { Database } from "@/lib/db/types";

// Assembles the full 12-stage kit as a single markdown document for export
// (spec §4.4). 12 H2 sections in stage order + the CRIT-4 MIT footer. Stages
// 1–2 are synthesized from the run; 3–12 come from the JSONB columns.

type RunRow = Database["public"]["Tables"]["pipeline_runs"]["Row"];

const MIT_FOOTER =
  "*Generated by YouTube Viralizer. Prompt patterns adapted from [AgriciDaniel/claude-youtube](https://github.com/AgriciDaniel/claude-youtube) under the MIT license. See ATTRIBUTIONS.md in the source repository.*";

// stage number → [heading, the run column it reads (null for synthesized 1–2)]
const STAGES: Array<[number, string, keyof RunRow | null]> = [
  [1, "Channel onboarding", null],
  [2, "Idea", null],
  [3, "Competitor outliers", "competitor_data"],
  [4, "Virality score", "score_data"],
  [5, "Titles", "titles_data"],
  [6, "Cold-open hook", "hook_data"],
  [7, "Retention script", "script_data"],
  [8, "Anti-pattern lint", "lint_data"],
  [9, "Thumbnail briefs", "thumbnails_data"],
  [10, "SEO metadata", "seo_data"],
  [11, "A/B test plan", "ab_plan_data"],
  [12, "Engagement drafts", "engagement_drafts_data"],
];

function jsonBlock(value: unknown): string {
  return ["```json", JSON.stringify(value, null, 2), "```"].join("\n");
}

export type KitBundle = { markdown: string; missingStages: number[] };

export function assembleKitMarkdown(run: RunRow): KitBundle {
  const missingStages: number[] = [];
  const sections: string[] = [`# YouTube Viralizer kit — ${run.idea_text}`, ""];

  for (const [num, heading, column] of STAGES) {
    sections.push(`## ${num}. ${heading}`);
    if (column === null) {
      sections.push(num === 2 ? run.idea_text : `Run \`${run.id}\` · channel \`${run.channel_id}\``);
    } else {
      const data = run[column];
      if (data === null) {
        missingStages.push(num);
        sections.push("_(not generated yet)_");
      } else {
        sections.push(jsonBlock(data));
      }
    }
    sections.push("");
  }

  sections.push("---", "", MIT_FOOTER);
  return { markdown: sections.join("\n"), missingStages };
}

export function kitFilename(run: RunRow): string {
  const slug = run.idea_text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `run-${run.id.slice(0, 8)}-${slug || "kit"}.md`;
}
