import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "YouTube Viralizer",
  description: "Turn one video idea into a 12-stage viral production kit.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <body className="antialiased">
        {children}
        <footer className="border-t border-white/5 text-ink-400 text-sm py-6 px-8 text-center">
          Generated by YouTube Viralizer. Prompt patterns adapted from{" "}
          <a
            href="https://github.com/AgriciDaniel/claude-youtube"
            className="underline hover:text-ink-200"
            target="_blank"
            rel="noopener noreferrer"
          >
            AgriciDaniel/claude-youtube
          </a>{" "}
          under the MIT license. See ATTRIBUTIONS.md in the source repository.
        </footer>
      </body>
    </html>
  );
}
